#!/usr/bin/env bash
# Generated by install-gates — canonical check entrypoint (SPEC R5).
# Runs the detected stack's stages in order and exits non-zero on the
# first failure, printing that command's output.
# Do not edit by hand; re-run install-gates to regenerate.
set -u
cd "$(dirname "$0")/.." || exit 1

run_stage() { # run_stage <name> <command...>
  desc="$1"; shift
  out="$("$@" 2>&1)"
  status=$?
  if [ "$status" -ne 0 ]; then
    printf 'check: %s failed:\n%s\n' "$desc" "$out" >&2
    exit "$status"
  fi
  printf 'check: %s ok\n' "$desc"
}

run_stage "format-check" bash -c 'files="$(gofmt -l .)"; [ -z "$files" ] || { printf "%s\n" "$files"; exit 1; }'
run_stage "lint" make vet
run_stage "tests" make test
exit 0
